### ISSUE TITLE
Error - File does not match folder

### ISSUE THREAD

**Issue by dixonge** [texnixe/kirby-code-editor#1]
Installed using Jen's Plugin Installer (https://github.com/jenstornell/kirby-plugin-installer) - does not seem to change anything in the panel and has this error:

![code-editor-error](https://user-images.githubusercontent.com/1578506/28123169-d7da42a8-66e5-11e7-8974-1956b3efdffa.png)

**Comment by dixonge** [comment]
took a chance - renamed the folder to just 'code-editor' and the error went away and the editor is in place!

**Comment by texnixe** [comment]
Yep, the foldername must always be the same as the (main) file in the plugin folder. It installs correctly when installed via the Kirby CLI.
